openapi: 3.0.3
info:
  title: OCR Bill Splitter API
  description: REST API for validating bill calculations and exporting results
  version: 1.0.0
  contact:
    name: Bill Splitter Team

servers:
  - url: http://localhost:8080/api
    description: Development server

paths:
  /bills/validate:
    post:
      summary: Validate bill calculations
      description: Validates bill split calculations for accuracy and consistency
      operationId: validateBill
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BillValidationRequest'
      responses:
        '200':
          description: Validation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillValidationResponse'
        '400':
          description: Invalid bill data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Calculation errors found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'

  /bills/calculate:
    post:
      summary: Calculate bill split
      description: Performs server-side calculation of bill split with decimal precision
      operationId: calculateBill
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BillCalculationRequest'
      responses:
        '200':
          description: Calculation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillCalculationResponse'
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /bills/{id}/export:
    get:
      summary: Export bill data
      description: Generate exportable formats for bill split results
      operationId: exportBill
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum: [json, csv, pdf]
            default: json
      responses:
        '200':
          description: Export successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportResponse'
            text/csv:
              schema:
                type: string
            application/pdf:
              schema:
                type: string
                format: binary
        '404':
          description: Bill not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    BillValidationRequest:
      type: object
      required:
        - lineItems
        - people
        - assignments
        - subtotal
        - taxAmount
        - tipAmount
        - totalAmount
      properties:
        lineItems:
          type: array
          items:
            $ref: '#/components/schemas/LineItem'
        people:
          type: array
          items:
            $ref: '#/components/schemas/Person'
        assignments:
          type: array
          items:
            $ref: '#/components/schemas/ItemAssignment'
        subtotal:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
          example: "45.67"
        taxAmount:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
          example: "3.65"
        tipAmount:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
          example: "9.13"
        totalAmount:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
          example: "58.45"

    BillValidationResponse:
      type: object
      required:
        - valid
        - calculatedTotals
      properties:
        valid:
          type: boolean
        calculatedTotals:
          type: object
          properties:
            subtotal:
              type: string
              pattern: '^[0-9]+\.[0-9]{2}$'
            taxAmount:
              type: string
              pattern: '^[0-9]+\.[0-9]{2}$'
            tipAmount:
              type: string
              pattern: '^[0-9]+\.[0-9]{2}$'
            totalAmount:
              type: string
              pattern: '^[0-9]+\.[0-9]{2}$'
        discrepancies:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              expected:
                type: string
              actual:
                type: string
              difference:
                type: string

    BillCalculationRequest:
      type: object
      required:
        - lineItems
        - assignments
        - taxRate
        - tipAmount
      properties:
        lineItems:
          type: array
          items:
            $ref: '#/components/schemas/LineItem'
        assignments:
          type: array
          items:
            $ref: '#/components/schemas/ItemAssignment'
        taxRate:
          type: string
          pattern: '^[0-9]+\.[0-9]{4}$'
          example: "0.1300"
          description: Tax rate as decimal (13% = 0.1300)
        tipAmount:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
          example: "9.13"

    BillCalculationResponse:
      type: object
      required:
        - summary
        - personTotals
        - calculations
      properties:
        summary:
          $ref: '#/components/schemas/BillSummary'
        personTotals:
          type: array
          items:
            $ref: '#/components/schemas/PersonTotal'
        calculations:
          type: object
          properties:
            subtotal:
              type: string
            taxAmount:
              type: string
            totalAmount:
              type: string
            timestamp:
              type: string
              format: date-time

    LineItem:
      type: object
      required:
        - id
        - name
        - quantity
        - unitPrice
        - totalPrice
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 255
        quantity:
          type: integer
          minimum: 1
        unitPrice:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
          example: "12.99"
        totalPrice:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
          example: "25.98"
        category:
          type: string
          nullable: true
        isShared:
          type: boolean
          default: false

    Person:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 100
        email:
          type: string
          format: email
          nullable: true
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          example: "#FF5733"

    ItemAssignment:
      type: object
      required:
        - lineItemId
        - personId
        - sharePercentage
      properties:
        lineItemId:
          type: string
          format: uuid
        personId:
          type: string
          format: uuid
        sharePercentage:
          type: string
          pattern: '^[0-1]\.[0-9]{4}$'
          example: "0.5000"
          description: Share as decimal (50% = 0.5000)

    BillSummary:
      type: object
      required:
        - subtotal
        - taxAmount
        - tipAmount
        - totalAmount
        - peopleCount
      properties:
        subtotal:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
        taxAmount:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
        tipAmount:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
        totalAmount:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
        peopleCount:
          type: integer
          minimum: 1
        calculatedAt:
          type: string
          format: date-time

    PersonTotal:
      type: object
      required:
        - personId
        - personName
        - subtotal
        - taxAmount
        - tipAmount
        - totalOwed
      properties:
        personId:
          type: string
          format: uuid
        personName:
          type: string
        subtotal:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
        taxAmount:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
        tipAmount:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'
        totalOwed:
          type: string
          pattern: '^[0-9]+\.[0-9]{2}$'

    ExportResponse:
      type: object
      required:
        - format
        - data
      properties:
        format:
          type: string
          enum: [json, csv, pdf]
        data:
          oneOf:
            - type: object
            - type: string
        generatedAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: array
          items:
            type: string

    ValidationErrorResponse:
      type: object
      required:
        - error
        - message
        - validationErrors
      properties:
        error:
          type: string
        message:
          type: string
        validationErrors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              code:
                type: string
              message:
                type: string
              expected:
                type: string
              actual:
                type: string